version: "3.8"
name: "projtest"
services:
  postgres:
    image:
      postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rfnz230691
      POSTGRES_DB: papa_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
  papa:
    depends_on:
      postgres:
        condition:
          service_healthy
    build:
      .
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app:ro
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  postgres_db: