version: "3.8"
name: "projtest"
services:
  postgres:
    image:
      postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
  papa:
    depends_on:
      postgres:
        condition:
          service_healthy
    image:
      antinormanist/fastpapa
    env_file:
      - ./.env
    ports:
      - "80:8000"
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000"

volumes:
  postgres_db: