name: Build and Deploy code

on:
  ["push", "pull_request"]

jobs:
  job1:
    env:
      SECRET_KEY:
        cd18c009a67b28f67c800aba797a62ef79ee96c5f0a694bf9dddb02dbcc26835
      ALGORITHM:
        HS256
      ACCESS_TOKEN_EXPIRE_MINUTES:
        60
      DB:
        postgresql+psycopg
      DB_USER:
        root
      DB_USER_PSWRD:
        rfnz230691
      DB_HOST:
        postgres
      DB_HOST_TEST:
        172.17.0.2
      DB_PORT:
        5432
      DB_NAME:
        papa_db
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Install Python3.12
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run pytest
        run: |
          pip install pytest
          pytest